# Generated by Django 5.2.6 on 2025-09-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='decision',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a related decision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.decision'),
        ),
    ]
