# Generated by Django 5.2.6 on 2025-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_deliverable_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_invitation', 'Event Invitation'), ('invitation_response', 'Invitation Response'), ('event_update', 'Event Update'), ('decision_created', 'Decision Created'), ('deliverable_assigned', 'Deliverable Assigned'), ('deliverable_due', 'Deliverable Due Soon'), ('system', 'System Notification')], default='system', max_length=20),
        ),
    ]
