# Generated by Django 5.2.6 on 2025-09-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_deliverables',
            field=models.BooleanField(default=True, help_text='Can manage assigned deliverables'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_invitations',
            field=models.BooleanField(default=True, help_text='Can manage event invitations'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_track_progress',
            field=models.BooleanField(default=True, help_text='Can track task progress'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_time_tracker',
            field=models.BooleanField(default=False, help_text='Can use time tracking features'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_calendar',
            field=models.BooleanField(default=True, help_text='Can access calendar view'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_decisions',
            field=models.BooleanField(default=False, help_text='Can view project decisions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_events',
            field=models.BooleanField(default=True, help_text='Can view and participate in events'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_projects',
            field=models.BooleanField(default=True, help_text='Can view assigned projects'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view personal reports'),
        ),
    ]
